common/debug.o: common/debug.c
common/debug.o: common/debug.h

common/entropy_common.o: common/bitstream.h
common/entropy_common.o: common/compiler.h
common/entropy_common.o: common/debug.h
common/entropy_common.o: common/entropy_common.c
common/entropy_common.o: common/error_private.h
common/entropy_common.o: common/fse.h
common/entropy_common.o: common/huf.h
common/entropy_common.o: common/mem.h
common/entropy_common.o: common/zstd_errors.h

common/error_private.o: common/error_private.c
common/error_private.o: common/error_private.h
common/error_private.o: common/zstd_errors.h

common/fse_decompress.o: common/bitstream.h
common/fse_decompress.o: common/compiler.h
common/fse_decompress.o: common/debug.h
common/fse_decompress.o: common/error_private.h
common/fse_decompress.o: common/fse.h
common/fse_decompress.o: common/fse_decompress.c
common/fse_decompress.o: common/mem.h
common/fse_decompress.o: common/zstd_errors.h

common/pool.o: common/bitstream.h
common/pool.o: common/compiler.h
common/pool.o: common/debug.h
common/pool.o: common/error_private.h
common/pool.o: common/fse.h
common/pool.o: common/huf.h
common/pool.o: common/mem.h
common/pool.o: common/pool.c
common/pool.o: common/pool.h
common/pool.o: common/threading.h
common/pool.o: common/xxhash.c
common/pool.o: common/xxhash.h
common/pool.o: common/zstd_errors.h
common/pool.o: common/zstd_internal.h
common/pool.o: zstd.h

common/threading.o: common/debug.h
common/threading.o: common/threading.c
common/threading.o: common/threading.h

common/xxhash.o: common/xxhash.c
common/xxhash.o: common/xxhash.h

common/zstd_common.o: common/bitstream.h
common/zstd_common.o: common/compiler.h
common/zstd_common.o: common/debug.h
common/zstd_common.o: common/error_private.h
common/zstd_common.o: common/fse.h
common/zstd_common.o: common/huf.h
common/zstd_common.o: common/mem.h
common/zstd_common.o: common/xxhash.c
common/zstd_common.o: common/xxhash.h
common/zstd_common.o: common/zstd_common.c
common/zstd_common.o: common/zstd_errors.h
common/zstd_common.o: common/zstd_internal.h
common/zstd_common.o: zstd.h

compress/fse_compress.o: common/bitstream.h
compress/fse_compress.o: common/compiler.h
compress/fse_compress.o: common/debug.h
compress/fse_compress.o: common/error_private.h
compress/fse_compress.o: common/fse.h
compress/fse_compress.o: common/mem.h
compress/fse_compress.o: common/zstd_errors.h
compress/fse_compress.o: compress/fse_compress.c
compress/fse_compress.o: compress/hist.h

compress/hist.o: common/debug.h
compress/hist.o: common/error_private.h
compress/hist.o: common/mem.h
compress/hist.o: common/zstd_errors.h
compress/hist.o: compress/hist.c
compress/hist.o: compress/hist.h

compress/huf_compress.o: common/bitstream.h
compress/huf_compress.o: common/compiler.h
compress/huf_compress.o: common/debug.h
compress/huf_compress.o: common/error_private.h
compress/huf_compress.o: common/fse.h
compress/huf_compress.o: common/huf.h
compress/huf_compress.o: common/mem.h
compress/huf_compress.o: common/zstd_errors.h
compress/huf_compress.o: compress/hist.h
compress/huf_compress.o: compress/huf_compress.c

compress/zstd_compress.o: common/bitstream.h
compress/zstd_compress.o: common/compiler.h
compress/zstd_compress.o: common/cpu.h
compress/zstd_compress.o: common/debug.h
compress/zstd_compress.o: common/error_private.h
compress/zstd_compress.o: common/fse.h
compress/zstd_compress.o: common/huf.h
compress/zstd_compress.o: common/mem.h
compress/zstd_compress.o: common/xxhash.c
compress/zstd_compress.o: common/xxhash.h
compress/zstd_compress.o: common/zstd_errors.h
compress/zstd_compress.o: common/zstd_internal.h
compress/zstd_compress.o: compress/hist.h
compress/zstd_compress.o: compress/zstd_compress.c
compress/zstd_compress.o: compress/zstd_compress_internal.h
compress/zstd_compress.o: compress/zstd_compress_literals.h
compress/zstd_compress.o: compress/zstd_compress_sequences.h
compress/zstd_compress.o: compress/zstd_compress_superblock.h
compress/zstd_compress.o: compress/zstd_cwksp.h
compress/zstd_compress.o: compress/zstd_double_fast.h
compress/zstd_compress.o: compress/zstd_fast.h
compress/zstd_compress.o: compress/zstd_lazy.h
compress/zstd_compress.o: compress/zstd_ldm.h
compress/zstd_compress.o: compress/zstd_opt.h
compress/zstd_compress.o: compress/zstdmt_compress.h
compress/zstd_compress.o: zstd.h

compress/zstd_compress_literals.o: common/bitstream.h
compress/zstd_compress_literals.o: common/compiler.h
compress/zstd_compress_literals.o: common/debug.h
compress/zstd_compress_literals.o: common/error_private.h
compress/zstd_compress_literals.o: common/fse.h
compress/zstd_compress_literals.o: common/huf.h
compress/zstd_compress_literals.o: common/mem.h
compress/zstd_compress_literals.o: common/xxhash.c
compress/zstd_compress_literals.o: common/xxhash.h
compress/zstd_compress_literals.o: common/zstd_errors.h
compress/zstd_compress_literals.o: common/zstd_internal.h
compress/zstd_compress_literals.o: compress/zstd_compress_internal.h
compress/zstd_compress_literals.o: compress/zstd_compress_literals.c
compress/zstd_compress_literals.o: compress/zstd_compress_literals.h
compress/zstd_compress_literals.o: compress/zstd_cwksp.h
compress/zstd_compress_literals.o: compress/zstdmt_compress.h
compress/zstd_compress_literals.o: zstd.h

compress/zstd_compress_sequences.o: common/bitstream.h
compress/zstd_compress_sequences.o: common/compiler.h
compress/zstd_compress_sequences.o: common/debug.h
compress/zstd_compress_sequences.o: common/error_private.h
compress/zstd_compress_sequences.o: common/fse.h
compress/zstd_compress_sequences.o: common/huf.h
compress/zstd_compress_sequences.o: common/mem.h
compress/zstd_compress_sequences.o: common/xxhash.c
compress/zstd_compress_sequences.o: common/xxhash.h
compress/zstd_compress_sequences.o: common/zstd_errors.h
compress/zstd_compress_sequences.o: common/zstd_internal.h
compress/zstd_compress_sequences.o: compress/zstd_compress_sequences.c
compress/zstd_compress_sequences.o: compress/zstd_compress_sequences.h
compress/zstd_compress_sequences.o: zstd.h

compress/zstd_compress_superblock.o: common/bitstream.h
compress/zstd_compress_superblock.o: common/compiler.h
compress/zstd_compress_superblock.o: common/debug.h
compress/zstd_compress_superblock.o: common/error_private.h
compress/zstd_compress_superblock.o: common/fse.h
compress/zstd_compress_superblock.o: common/huf.h
compress/zstd_compress_superblock.o: common/mem.h
compress/zstd_compress_superblock.o: common/xxhash.c
compress/zstd_compress_superblock.o: common/xxhash.h
compress/zstd_compress_superblock.o: common/zstd_errors.h
compress/zstd_compress_superblock.o: common/zstd_internal.h
compress/zstd_compress_superblock.o: compress/hist.h
compress/zstd_compress_superblock.o: compress/zstd_compress_internal.h
compress/zstd_compress_superblock.o: compress/zstd_compress_literals.h
compress/zstd_compress_superblock.o: compress/zstd_compress_sequences.h
compress/zstd_compress_superblock.o: compress/zstd_compress_superblock.c
compress/zstd_compress_superblock.o: compress/zstd_compress_superblock.h
compress/zstd_compress_superblock.o: compress/zstd_cwksp.h
compress/zstd_compress_superblock.o: compress/zstdmt_compress.h
compress/zstd_compress_superblock.o: zstd.h

compress/zstd_double_fast.o: common/bitstream.h
compress/zstd_double_fast.o: common/compiler.h
compress/zstd_double_fast.o: common/debug.h
compress/zstd_double_fast.o: common/error_private.h
compress/zstd_double_fast.o: common/fse.h
compress/zstd_double_fast.o: common/huf.h
compress/zstd_double_fast.o: common/mem.h
compress/zstd_double_fast.o: common/xxhash.c
compress/zstd_double_fast.o: common/xxhash.h
compress/zstd_double_fast.o: common/zstd_errors.h
compress/zstd_double_fast.o: common/zstd_internal.h
compress/zstd_double_fast.o: compress/zstd_compress_internal.h
compress/zstd_double_fast.o: compress/zstd_cwksp.h
compress/zstd_double_fast.o: compress/zstd_double_fast.c
compress/zstd_double_fast.o: compress/zstd_double_fast.h
compress/zstd_double_fast.o: compress/zstdmt_compress.h
compress/zstd_double_fast.o: zstd.h

compress/zstd_fast.o: common/bitstream.h
compress/zstd_fast.o: common/compiler.h
compress/zstd_fast.o: common/debug.h
compress/zstd_fast.o: common/error_private.h
compress/zstd_fast.o: common/fse.h
compress/zstd_fast.o: common/huf.h
compress/zstd_fast.o: common/mem.h
compress/zstd_fast.o: common/xxhash.c
compress/zstd_fast.o: common/xxhash.h
compress/zstd_fast.o: common/zstd_errors.h
compress/zstd_fast.o: common/zstd_internal.h
compress/zstd_fast.o: compress/zstd_compress_internal.h
compress/zstd_fast.o: compress/zstd_cwksp.h
compress/zstd_fast.o: compress/zstd_fast.c
compress/zstd_fast.o: compress/zstd_fast.h
compress/zstd_fast.o: compress/zstdmt_compress.h
compress/zstd_fast.o: zstd.h

compress/zstd_lazy.o: common/bitstream.h
compress/zstd_lazy.o: common/compiler.h
compress/zstd_lazy.o: common/debug.h
compress/zstd_lazy.o: common/error_private.h
compress/zstd_lazy.o: common/fse.h
compress/zstd_lazy.o: common/huf.h
compress/zstd_lazy.o: common/mem.h
compress/zstd_lazy.o: common/xxhash.c
compress/zstd_lazy.o: common/xxhash.h
compress/zstd_lazy.o: common/zstd_errors.h
compress/zstd_lazy.o: common/zstd_internal.h
compress/zstd_lazy.o: compress/zstd_compress_internal.h
compress/zstd_lazy.o: compress/zstd_cwksp.h
compress/zstd_lazy.o: compress/zstd_lazy.c
compress/zstd_lazy.o: compress/zstd_lazy.h
compress/zstd_lazy.o: compress/zstdmt_compress.h
compress/zstd_lazy.o: zstd.h

compress/zstd_ldm.o: common/bitstream.h
compress/zstd_ldm.o: common/compiler.h
compress/zstd_ldm.o: common/debug.h
compress/zstd_ldm.o: common/error_private.h
compress/zstd_ldm.o: common/fse.h
compress/zstd_ldm.o: common/huf.h
compress/zstd_ldm.o: common/mem.h
compress/zstd_ldm.o: common/xxhash.c
compress/zstd_ldm.o: common/xxhash.h
compress/zstd_ldm.o: common/zstd_errors.h
compress/zstd_ldm.o: common/zstd_internal.h
compress/zstd_ldm.o: compress/zstd_compress_internal.h
compress/zstd_ldm.o: compress/zstd_cwksp.h
compress/zstd_ldm.o: compress/zstd_double_fast.h
compress/zstd_ldm.o: compress/zstd_fast.h
compress/zstd_ldm.o: compress/zstd_ldm.c
compress/zstd_ldm.o: compress/zstd_ldm.h
compress/zstd_ldm.o: compress/zstdmt_compress.h
compress/zstd_ldm.o: zstd.h

compress/zstd_opt.o: common/bitstream.h
compress/zstd_opt.o: common/compiler.h
compress/zstd_opt.o: common/debug.h
compress/zstd_opt.o: common/error_private.h
compress/zstd_opt.o: common/fse.h
compress/zstd_opt.o: common/huf.h
compress/zstd_opt.o: common/mem.h
compress/zstd_opt.o: common/xxhash.c
compress/zstd_opt.o: common/xxhash.h
compress/zstd_opt.o: common/zstd_errors.h
compress/zstd_opt.o: common/zstd_internal.h
compress/zstd_opt.o: compress/hist.h
compress/zstd_opt.o: compress/zstd_compress_internal.h
compress/zstd_opt.o: compress/zstd_cwksp.h
compress/zstd_opt.o: compress/zstd_opt.c
compress/zstd_opt.o: compress/zstd_opt.h
compress/zstd_opt.o: compress/zstdmt_compress.h
compress/zstd_opt.o: zstd.h

compress/zstdmt_compress.o: common/bitstream.h
compress/zstdmt_compress.o: common/compiler.h
compress/zstdmt_compress.o: common/debug.h
compress/zstdmt_compress.o: common/error_private.h
compress/zstdmt_compress.o: common/fse.h
compress/zstdmt_compress.o: common/huf.h
compress/zstdmt_compress.o: common/mem.h
compress/zstdmt_compress.o: common/pool.h
compress/zstdmt_compress.o: common/threading.h
compress/zstdmt_compress.o: common/xxhash.c
compress/zstdmt_compress.o: common/xxhash.h
compress/zstdmt_compress.o: common/zstd_errors.h
compress/zstdmt_compress.o: common/zstd_internal.h
compress/zstdmt_compress.o: compress/zstd_compress_internal.h
compress/zstdmt_compress.o: compress/zstd_cwksp.h
compress/zstdmt_compress.o: compress/zstd_ldm.h
compress/zstdmt_compress.o: compress/zstdmt_compress.c
compress/zstdmt_compress.o: compress/zstdmt_compress.h
compress/zstdmt_compress.o: zstd.h

decompress/huf_decompress.o: common/bitstream.h
decompress/huf_decompress.o: common/compiler.h
decompress/huf_decompress.o: common/debug.h
decompress/huf_decompress.o: common/error_private.h
decompress/huf_decompress.o: common/fse.h
decompress/huf_decompress.o: common/huf.h
decompress/huf_decompress.o: common/mem.h
decompress/huf_decompress.o: common/zstd_errors.h
decompress/huf_decompress.o: decompress/huf_decompress.c

decompress/zstd_ddict.o: common/bitstream.h
decompress/zstd_ddict.o: common/compiler.h
decompress/zstd_ddict.o: common/cpu.h
decompress/zstd_ddict.o: common/debug.h
decompress/zstd_ddict.o: common/error_private.h
decompress/zstd_ddict.o: common/fse.h
decompress/zstd_ddict.o: common/huf.h
decompress/zstd_ddict.o: common/mem.h
decompress/zstd_ddict.o: common/xxhash.c
decompress/zstd_ddict.o: common/xxhash.h
decompress/zstd_ddict.o: common/zstd_errors.h
decompress/zstd_ddict.o: common/zstd_internal.h
decompress/zstd_ddict.o: decompress/zstd_ddict.c
decompress/zstd_ddict.o: decompress/zstd_ddict.h
decompress/zstd_ddict.o: decompress/zstd_decompress_internal.h
decompress/zstd_ddict.o: legacy/zstd_legacy.h
decompress/zstd_ddict.o: legacy/zstd_v01.h
decompress/zstd_ddict.o: legacy/zstd_v02.h
decompress/zstd_ddict.o: legacy/zstd_v03.h
decompress/zstd_ddict.o: legacy/zstd_v04.h
decompress/zstd_ddict.o: legacy/zstd_v05.h
decompress/zstd_ddict.o: legacy/zstd_v06.h
decompress/zstd_ddict.o: legacy/zstd_v07.h
decompress/zstd_ddict.o: zstd.h

decompress/zstd_decompress.o: common/bitstream.h
decompress/zstd_decompress.o: common/compiler.h
decompress/zstd_decompress.o: common/cpu.h
decompress/zstd_decompress.o: common/debug.h
decompress/zstd_decompress.o: common/error_private.h
decompress/zstd_decompress.o: common/fse.h
decompress/zstd_decompress.o: common/huf.h
decompress/zstd_decompress.o: common/mem.h
decompress/zstd_decompress.o: common/xxhash.c
decompress/zstd_decompress.o: common/xxhash.h
decompress/zstd_decompress.o: common/zstd_errors.h
decompress/zstd_decompress.o: common/zstd_internal.h
decompress/zstd_decompress.o: decompress/zstd_ddict.h
decompress/zstd_decompress.o: decompress/zstd_decompress.c
decompress/zstd_decompress.o: decompress/zstd_decompress_block.h
decompress/zstd_decompress.o: decompress/zstd_decompress_internal.h
decompress/zstd_decompress.o: legacy/zstd_legacy.h
decompress/zstd_decompress.o: legacy/zstd_v01.h
decompress/zstd_decompress.o: legacy/zstd_v02.h
decompress/zstd_decompress.o: legacy/zstd_v03.h
decompress/zstd_decompress.o: legacy/zstd_v04.h
decompress/zstd_decompress.o: legacy/zstd_v05.h
decompress/zstd_decompress.o: legacy/zstd_v06.h
decompress/zstd_decompress.o: legacy/zstd_v07.h
decompress/zstd_decompress.o: zstd.h

decompress/zstd_decompress_block.o: common/bitstream.h
decompress/zstd_decompress_block.o: common/compiler.h
decompress/zstd_decompress_block.o: common/cpu.h
decompress/zstd_decompress_block.o: common/debug.h
decompress/zstd_decompress_block.o: common/error_private.h
decompress/zstd_decompress_block.o: common/fse.h
decompress/zstd_decompress_block.o: common/huf.h
decompress/zstd_decompress_block.o: common/mem.h
decompress/zstd_decompress_block.o: common/xxhash.c
decompress/zstd_decompress_block.o: common/xxhash.h
decompress/zstd_decompress_block.o: common/zstd_errors.h
decompress/zstd_decompress_block.o: common/zstd_internal.h
decompress/zstd_decompress_block.o: decompress/zstd_ddict.h
decompress/zstd_decompress_block.o: decompress/zstd_decompress_block.c
decompress/zstd_decompress_block.o: decompress/zstd_decompress_block.h
decompress/zstd_decompress_block.o: decompress/zstd_decompress_internal.h
decompress/zstd_decompress_block.o: zstd.h

deprecated/zbuff_common.o: common/error_private.h
deprecated/zbuff_common.o: common/zstd_errors.h
deprecated/zbuff_common.o: deprecated/zbuff.h
deprecated/zbuff_common.o: deprecated/zbuff_common.c
deprecated/zbuff_common.o: zstd.h

deprecated/zbuff_compress.o: deprecated/zbuff.h
deprecated/zbuff_compress.o: deprecated/zbuff_compress.c
deprecated/zbuff_compress.o: zstd.h

deprecated/zbuff_decompress.o: deprecated/zbuff.h
deprecated/zbuff_decompress.o: deprecated/zbuff_decompress.c
deprecated/zbuff_decompress.o: zstd.h

dictBuilder/cover.o: common/bitstream.h
dictBuilder/cover.o: common/compiler.h
dictBuilder/cover.o: common/debug.h
dictBuilder/cover.o: common/error_private.h
dictBuilder/cover.o: common/fse.h
dictBuilder/cover.o: common/huf.h
dictBuilder/cover.o: common/mem.h
dictBuilder/cover.o: common/pool.h
dictBuilder/cover.o: common/threading.h
dictBuilder/cover.o: common/xxhash.c
dictBuilder/cover.o: common/xxhash.h
dictBuilder/cover.o: common/zstd_errors.h
dictBuilder/cover.o: common/zstd_internal.h
dictBuilder/cover.o: dictBuilder/cover.c
dictBuilder/cover.o: dictBuilder/cover.h
dictBuilder/cover.o: dictBuilder/zdict.h
dictBuilder/cover.o: zstd.h

dictBuilder/divsufsort.o: dictBuilder/divsufsort.c
dictBuilder/divsufsort.o: dictBuilder/divsufsort.h

dictBuilder/fastcover.o: common/bitstream.h
dictBuilder/fastcover.o: common/compiler.h
dictBuilder/fastcover.o: common/debug.h
dictBuilder/fastcover.o: common/error_private.h
dictBuilder/fastcover.o: common/fse.h
dictBuilder/fastcover.o: common/huf.h
dictBuilder/fastcover.o: common/mem.h
dictBuilder/fastcover.o: common/pool.h
dictBuilder/fastcover.o: common/threading.h
dictBuilder/fastcover.o: common/xxhash.c
dictBuilder/fastcover.o: common/xxhash.h
dictBuilder/fastcover.o: common/zstd_errors.h
dictBuilder/fastcover.o: common/zstd_internal.h
dictBuilder/fastcover.o: dictBuilder/cover.h
dictBuilder/fastcover.o: dictBuilder/fastcover.c
dictBuilder/fastcover.o: dictBuilder/zdict.h
dictBuilder/fastcover.o: zstd.h

dictBuilder/zdict.o: common/bitstream.h
dictBuilder/zdict.o: common/compiler.h
dictBuilder/zdict.o: common/debug.h
dictBuilder/zdict.o: common/error_private.h
dictBuilder/zdict.o: common/fse.h
dictBuilder/zdict.o: common/huf.h
dictBuilder/zdict.o: common/mem.h
dictBuilder/zdict.o: common/xxhash.c
dictBuilder/zdict.o: common/xxhash.h
dictBuilder/zdict.o: common/zstd_errors.h
dictBuilder/zdict.o: common/zstd_internal.h
dictBuilder/zdict.o: compress/zstd_compress_internal.h
dictBuilder/zdict.o: compress/zstd_cwksp.h
dictBuilder/zdict.o: compress/zstdmt_compress.h
dictBuilder/zdict.o: dictBuilder/divsufsort.h
dictBuilder/zdict.o: dictBuilder/zdict.c
dictBuilder/zdict.o: dictBuilder/zdict.h
dictBuilder/zdict.o: zstd.h

